// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzjcbqwffrnpgebuntvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56amNicXdmZnJucGdlYnVudHZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMDM1MTEsImV4cCI6MjA2ODg3OTUxMX0._Fen0_Z8QvoNkVLCd6tcM1JHHrSRmF2xlIRmVAGQY10";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});